<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageVersion Include="lobirod.core" Version="0.0.1" />
    <PackageVersion Include="lobirod.fileservice.contracts" Version="0.0.1" />
    <PackageVersion Include="lobirod.framework" Version="0.0.1" />
    <PackageVersion Include="lobirod.sharedkernel" Version="0.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.10.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>