<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageVersion Include="lobirod.core" Version="0.0.1" />
    <PackageVersion Include="lobirod.framework" Version="0.0.1" />
    <PackageVersion Include="lobirod.sharedkernel" Version="0.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
  </ItemGroup>
</Project>